MF global header changes [ staging ] #4271
vc4a-dev/vc4a-styles pull request #110
Opened 2022-01-20 17:55 UTC by matt-vc4a

- font weight set to semibold on nav buttons
- search results break on ellipsis instead of wrapping now
- search results `-type` element styled correctly now
- mixin added for label styles
- better selector added for cmt-banner issue

2022-01-20 18:19 UTC, xoref approved these changes

2022-01-21 09:15 UTC, olufemioye requested changes

2022-01-21 09:15 UTC, olufemioye commented on scss/00-core/_typography.scss
> +  @include base-label-styles;
@matt-vc4a Is there any reason for this update for this PR?

2022-01-21 09:34 UTC, olufemioye approved these changes

2022-01-21 09:43 UTC, merged