Fo accordion a11y #65
vc4a-dev/vc4a-styles pull request #151
Opened 2022-05-19 12:59 UTC by olufemioye

# Description
- Updated accordion style.
- Added a11y attribute to the documentation.

Fixes https://github.com/vc4a-dev/plan/issues/65

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2022-05-19 13:08 UTC, merged

2022-05-19 13:09 UTC, matt-vc4a requested changes

2022-05-19 13:09 UTC, matt-vc4a commented on scss/02-molecule/_accordion.scss
> +    display: block;
is this going to work with the flex-grow?

Maybe one of them needs to be removed

2022-05-19 13:09 UTC, matt-vc4a commented on docs/molecules/accordion.html
> +                        <div class="accordion__body" aria-expanded="true">
So this is the thing I was saying about us being wrong about where to put aria-expanded

It should be on the button you click, not the element that is expanded.

Also you need the JS to change it at the appropriate time (I don't see the JS being updated here)

![image](https://user-images.githubusercontent.com/88677200/169300762-19a8bae3-ab68-4b5a-b2d4-28f66551053a.png)







### [ [documentation link](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-expanded) ]

2022-05-19 13:14 UTC, olufemioye commented on scss/02-molecule/_accordion.scss
> +    display: block;
This will work. I added `block` as a display property because the default tag is now a `span`.

2022-05-19 15:57 UTC, xoref commented
@olufemioye There is no PR for production yet?

2022-05-19 16:08 UTC, xoref commented on docs/molecules/accordion.html
> +                        <div class="accordion__body" aria-expanded="true">
it's a bit confusing tho after reading this:
> For example, `aria-expanded` is applied **to the parent item** in a DOM tree to indicate whether its child branch is shown. The parent controls the visibility of the associated child branch, as well.

2022-05-20 11:48 UTC, matt-vc4a commented on docs/molecules/accordion.html
> +                        <div class="accordion__body" aria-expanded="true">
https://www.w3.org/WAI/GL/wiki/Using_the_WAI-ARIA_aria-expanded_state_to_mark_expandable_and_collapsible_regions

<img width="1106" alt="image" src="https://user-images.githubusercontent.com/88677200/169515120-40a4c079-97fe-478e-b53e-61a29af76e6a.png">