[ Storybook ] Install Storybook for design system - 712 & 713 [ Prod ]
vc4a-dev/vc4a-styles pull request #194
Opened 2024-02-09 14:54 UTC by bolade-oye

# Description

Install Storybook, Vue3, and Vite (for the design system) on styles. It's a large PR and contains a lot of default files from storybook. I only made updates to the following:
 - `.gitignore`: Added recommended ignore options
 -  `README.md`: Updated it to include the command to run storybook
 - `package.json` files: Did a merge between already existing package.json file and new dependencies 
 
 
## Screenshot
 ![image](https://github.com/vc4a-dev/vc4a-styles/assets/58289075/556ecdef-be8b-41ca-bcc8-2f868baaf410)

Fixes vc4a-dev/plan#712 & vc4a-dev/plan#713

2024-02-09 15:31 UTC, matt-vc4a requested changes
mainly questions about what to do with the demo files that come pre-made

2024-02-09 15:31 UTC, matt-vc4a commented on index.html
> +<!doctype html>
Is this file needed?

2024-02-09 15:31 UTC, matt-vc4a commented on src/App.vue
> +<script setup>
needed?

or is this the base you'll work from?

2024-02-09 15:31 UTC, matt-vc4a commented on src/components/HelloWorld.vue
> +<script setup>
also needed?

2024-02-09 15:31 UTC, matt-vc4a commented on src/stories/Button.vue
> +        'storybook-button': true,
why the `storybook-` prefix?

2024-02-09 15:31 UTC, matt-vc4a commented on src/stories/Configure.mdx
> +import { Meta } from "@storybook/blocks";
what's this? a tutorial page?

2024-02-09 15:31 UTC, matt-vc4a commented on src/stories/Header.stories.js
> +import MyHeader from './Header.vue';
another tutorial/example?

2024-02-09 15:31 UTC, matt-vc4a commented on src/stories/assets/accessibility.png
Can these example files be removed? If we wait too long they'll stay there forever

2024-02-09 15:31 UTC, matt-vc4a commented on src/style.css
> +:root {
if you remove the example files, don't forget their css too

2024-02-12 09:17 UTC, bolade-oye commented on index.html
> +<!doctype html>
Yes, This is needed for Vue to run

2024-02-12 09:17 UTC, bolade-oye commented on src/App.vue
> +<script setup>
This is also needed for Vue to run

2024-02-12 10:11 UTC, bolade-oye commented on src/components/HelloWorld.vue
> +<script setup>
Removed. https://github.com/vc4a-dev/vc4a-styles/pull/194/commits/4bd81316722f32a9a21b531f0e44ffb697e4100e

2024-02-12 10:11 UTC, bolade-oye commented on src/stories/Button.vue
> +        'storybook-button': true,
It's a tutorial file https://github.com/vc4a-dev/vc4a-styles/pull/194/commits/9966dc63d530bd49f2a39fc1cc24d499e397e145

2024-02-12 10:11 UTC, bolade-oye commented on src/stories/Configure.mdx
> +import { Meta } from "@storybook/blocks";
Yes, I've added a comment to the first line fo each tutorial file https://github.com/vc4a-dev/vc4a-styles/pull/194/commits/9966dc63d530bd49f2a39fc1cc24d499e397e145

2024-02-12 10:12 UTC, bolade-oye commented on src/stories/Header.stories.js
> +import MyHeader from './Header.vue';
Yes, Added a comment https://github.com/vc4a-dev/vc4a-styles/pull/194/commits/9966dc63d530bd49f2a39fc1cc24d499e397e145

2024-02-12 10:12 UTC, bolade-oye commented on src/stories/assets/accessibility.png
I'll remove them when taking out the tutorial files

2024-02-12 10:51 UTC, matt-vc4a approved these changes

2024-02-12 14:26 UTC, merged