Bo Fix button size change on hover [ Staging ]
vc4a-dev/vc4a-styles pull request #92
Opened 2021-12-14 11:38 UTC by bolade-oye

# Description
- Fix issue where button size changes on hover

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2021-12-14 15:08 UTC, matt-vc4a commented on scss/01-atom/_button.scss
> +  @extend %btn-common;
@bolade-oye please stick with the mixin (and change the mixin if you need anything changed)

Extending high-level elements like this can get messy fast, so isn't really scaleable (the mixin is deliberate)

2021-12-14 15:10 UTC, matt-vc4a commented on scss/01-atom/_button.scss
> +  @extend %btn-common;
Remember other elements will be including this mixin to mimic the button styles, so please put everything from `.btn` into `btn-base-styles`

2021-12-14 15:10 UTC, matt-vc4a requested changes
Important fixes.

2021-12-15 12:00 UTC, matt-vc4a commented on scss/00-core/_mixins.scss
> +  @include btn-size($btn-padding-md, $btn-font-size-md, $btn-height-md);
Are you sure it's OK to remove these?

I put them there so that the .less styles didn't override them.

I checked out the code and it seems to be good though, so I am curious what changed since then.

However a quick test shows that the ":active" state causes the padding to change (so basically the button changes size for half a second when it is clicked. Probably a minor bug though.

2021-12-15 12:10 UTC, matt-vc4a requested changes
A couple of things

2021-12-15 12:10 UTC, matt-vc4a commented on scss/00-core/_mixins.scss
> +  @include btn-size($btn-padding-md, $btn-font-size-md, $btn-height-md);
Ah I see you moved it to mixins.scss. Nice.

2021-12-15 12:10 UTC, matt-vc4a commented on scss/00-core/_variables.scss
> +$btn-padding-sm: $spacing-03 $spacing-04;
Please do these as mixins in mixins.scss

You can either make new mixins

```@mixin base-btn-sm-styles```

or build onto the regular mixin

```
@mixin base-btn-styles($size: default) {
    // current style rules
    @if($size === sm) {
        // sm styles
    } elseif(etc...)
}
```

The size: default just means that the old uses of it (without a size argument) won't break.

2021-12-15 13:02 UTC, matt-vc4a commented on scss/00-core/_mixins.scss
> +@mixin btn-size ($padding, $font-size,  $height) {
@bolade-oye I meant more that you would call it like 

```@include base-btn-styles(sm);```

and then the values could be inside it. It just means that the work is all done by the mixin, not the person @including it.

It works for now, but so it is clear what this mixin does, can you call it `btn-custom-size` instead?

Also, it can often help backwards compatibility to give default values for parameters.

```@mixin btn-custom-size ($padding: 0.5rem, $font-size: 1rem,  $height: 1rem)```

or whatever. Then people only have to include the arguments they want to change.

2021-12-15 13:04 UTC, matt-vc4a requested changes
Just some tweaks

2021-12-15 15:15 UTC, matt-vc4a approved these changes

2021-12-15 15:17 UTC, xoref commented on scss/00-core/_mixins.scss
> +@mixin btn-size ($padding, $font-size,  $height) {
@matt-vc4a you've approved the PR, but shouldn't this be fixed first?

2021-12-15 15:40 UTC, xoref approved these changes

2021-12-15 15:40 UTC, merged